/** Max upload size enforced in Storage rules and client-side (15 MB). */
export const MAX_UPLOAD_BYTES = 15 * 1024 * 1024;

/** Responsive widths generated by the Cloud Function. */
export const IMAGE_WIDTHS = [400, 800, 1200];

/** Firestore field updated by the image-processing Cloud Function per collection. */
export const COLLECTION_IMAGE_FIELD = {
  anunturi: "imagine_url",
  membri_echipa: "poza_url",
  membri_consiliu: "poza_url",
  galerie_poze: "url",
};

export function uploadStoragePath(collection, docId) {
  return `uploads/${collection}/${docId}/original.jpg`;
}

/** Builds a srcSet string from a processed image URL (400/800/1200.webp, shared token). */
export function imageSrcSet(url) {
  if (!url || !url.includes("/uploads") || !url.includes(".webp")) return undefined;
  return IMAGE_WIDTHS.map((w) => `${url.replace(/400|800|1200(?=\.webp)/, String(w))} ${w}w`).join(", ");
}

export function imageUrlForWidth(url, width = 800) {
  if (!url || !url.includes("/uploads") || !url.includes(".webp")) return url;
  return url.replace(/400|800|1200(?=\.webp)/, String(width));
}

export function formatUploadError(err) {
  const code = err?.code || "";
  if (code === "storage/unauthorized" || code === "storage/permission-denied") {
    return "Nu ai permisiunea să încarci poze. Te rog reconectează-te.";
  }
  if (code === "storage/canceled") {
    return "Încărcarea a fost anulată.";
  }
  if (code === "storage/quota-exceeded") {
    return "Spatiul de stocare este plin. Contactează administratorul site-ului.";
  }
  if (err?.message?.includes("15 MB") || err?.message?.includes("prea mare")) {
    return err.message;
  }
  return "Nu am putut încărca poza. Te rog încearcă din nou cu o altă imagine.";
}
